version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/decipherability-generator

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn build
      - run: yarn deploy decipherability.lalilo.com
